apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web-api-v1
spec:
  selector:
    matchLabels:
      app: web-api
      version: v1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-api
        version: v1
    spec:
      containers:
      - image: web-api:v1
        name: web-api
        ports:
        - containerPort: 3000
          name: web-api
      restartPolicy: Always    
---
