apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web-api-v2
spec:
  selector:
    matchLabels:
      app: web-api
      version: v2
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-api
        version: v2
    spec:
      containers:
      - image: web-api:v2
        name: web-api-v2
        ports:
        - containerPort: 3000
          name: http
      restartPolicy: Always    
---
